---
title: "IL-IO"
date: 2018-12-28
---

title: IL-IO
author: Igor Lucas
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Descrição do meu site.

# social links
twitter_username: IgorLuc07225414
github_username:  igorlucas

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
